### ISSUE TITLE
Use helper createContentDigest

### ISSUE THREAD

**Issue by muescha** [jlengstorf/gatsby-source-pixabay#1]
it should use the helper createContentDigest

https://github.com/jlengstorf/gatsby-source-pixabay/blob/8660d3dab8a5f4fb7deae21ca03a28fdf22a5573/src/gatsby-node.js#L22-L25

**Comment by jlengstorf** [comment]
@muescha good call. If you want to PR this, that would be great!

**Comment by muescha** [comment]
i tried it - but it is not tested by me and i only edit it on github :(
